Wrap JSON of ENV AIRFLOW__SECRETS__BACKEND_KWARGS with single quotes (#1538)
* Wrap JSON of ENV AIRFLOW__SECRETS__BACKEND_KWARGS with single quotes

Trying the Airflow secrets for Azure.  On my Mac I was getting this error ```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: Syntax error - can't find = in "\"airflow-connections\",". Must be of the form: name=value
Error: command 'docker build -t astro-hello-world_ee2ff6/airflow:latest failed: failed to execute cmd: exit status 1
```

I had to perform the proposed change where I wrapped the JSON with single quotes

* Apply single quotes/ env var-friendly format to other setups

* Simplify AWS setups

* Simplify instructions, remove the need to interact with Dockerfile

* Apply suggestions from code review

* Apply suggestions from code review

Co-authored-by: Jake Witz <74574233+jwitz@users.noreply.github.com>